### ISSUE TITLE
LEXICON not defined

### ISSUE THREAD

**Issue by seffw** [ekinhbayar/BrillTagger#7]
Just a quick note for anyone using this. Lexicon needs to be defined somewhere. This isn't usable code as it. Looks like a great start though for contributors to correct what's missing

**Comment by ekinhbayar** [comment]
Hi, did you run composer install? The constant LEXICON is defined upon composer install, as it is listed [here](https://github.com/ekinhbayar/BrillTagger/blob/master/composer.json#L24). I've added this note in the project readme now to make it clear. If after composer install you have a missing lexicon, let me know, I'll reopen this issue.
